leftnav:
- identifier: 0648bfcc-712f-4c2c-9200-0c39558ad741
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 5041c800-611b-4260-a0b8-fec58f9a3304
  name: Instructor Insights
  weight: 20
- identifier: 88826513-005e-4263-9977-43156297dfde
  name: Lecture Summaries
  pageRef: /pages/lecture-summaries
  weight: 30
- identifier: 67f70336-772c-4fd5-b8bd-c758fda1e246
  name: Readings
  pageRef: /pages/readings
  weight: 40
- identifier: 8867580c-2494-4c16-94ab-9d7b617e0df8
  name: Assignments
  pageRef: /pages/assignments
  weight: 50
- identifier: cf6a19b7-fcff-4b57-be5a-dc2e201b6960
  name: Study Materials
  pageRef: /pages/study-materials
  weight: 60
